### ISSUE TITLE
Do you have a solid impossible value?

### ISSUE THREAD

**Issue by BlakeJohnCarter** [rstorr/326#9]

**Comment by rstorr** [comment]
The program is still buggy shouldn't of been merged, my bad! Don't understand your question though.

**Comment by BlakeJohnCarter** [comment]
when does the program decide when the calculation is impossible?

**Comment by rstorr** [comment]
Look at the code, if findFormula does not add anything to correctOperations list then there is no correct operations and 'impossible' is printed
